### PR TITLE
Update bot.ts

### PR DESCRIPTION
**Pull request by dheereshag**
there was a bug

### CODE REVIEW

**Comment by tylerlong** [comment]
Could you please elaborate how to reproduce the bug?

I have this demo project which just works: https://github.com/tylerlong/ringcentral-chatbot-dialog-demo

Appreciate if you could tell me how to reproduce the bug with the project above. Thanks.

**Comment by dheereshag** [comment]
If you go to the package.json, it installs the ringcentral bot itself. The problem is in the ringcentral-chatbot-js

**Comment by tylerlong** [comment]
They are the same thing: 
- https://www.npmjs.com/package/ringcentral-chatbot
- https://github.com/ringcentral/ringcentral-chatbot-js

**Comment by dheereshag** [comment]
Yeah, that I know, but the current code throws an error "Can't verify the redirect uri" when we add the bot without the line I added in bot.ts

**Comment by tylerlong** [comment]
The part you changed has no effect on bot adding.
I believe it is just a coincidence that you made the change and it worked.

What affect bot adding is this part: https://github.com/ringcentral/ringcentral-chatbot-js/blob/master/src/apps/bot.ts#L10-L18

Again, steps to reproduce the issue are required. I don't want to make change without verifying it first.

**Comment by dheereshag** [comment]
I will install it from the scratch, and reproduce the bug. Could we connect today as early as possible because of the timezone difference?

**Comment by tylerlong** [comment]
I tested it in production but I couldn't reproduce the issue.  And yes there seems be to an issue in sandbox environment. I will go ahead and merge this PR.

**Pull request merged**
